// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic
{
    public static class GetCseLogMappingVendorProduct
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using SumoLogic = Pulumi.SumoLogic;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var webGateway = SumoLogic.GetCseLogMappingVendorProduct.Invoke(new()
        ///     {
        ///         Product = "Web Gateway",
        ///         Vendor = "McAfee",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// A Log mapping vendor product can be looked up by providing values of `product` and `vendor`
        /// Both `product` and `vendor` values are mandatory. If not provided an error will be generated.
        /// 
        /// ## Attributes reference
        /// 
        /// The following attributes are exported:
        /// 
        /// - `guid` - The internal GUID of the log mapping vendor product.
        /// - `product` - The name of the product.
        /// - `vendor` - The name of the vendor.
        /// </summary>
        public static Task<GetCseLogMappingVendorProductResult> InvokeAsync(GetCseLogMappingVendorProductArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCseLogMappingVendorProductResult>("sumologic:index/getCseLogMappingVendorProduct:getCseLogMappingVendorProduct", args ?? new GetCseLogMappingVendorProductArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using SumoLogic = Pulumi.SumoLogic;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var webGateway = SumoLogic.GetCseLogMappingVendorProduct.Invoke(new()
        ///     {
        ///         Product = "Web Gateway",
        ///         Vendor = "McAfee",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// A Log mapping vendor product can be looked up by providing values of `product` and `vendor`
        /// Both `product` and `vendor` values are mandatory. If not provided an error will be generated.
        /// 
        /// ## Attributes reference
        /// 
        /// The following attributes are exported:
        /// 
        /// - `guid` - The internal GUID of the log mapping vendor product.
        /// - `product` - The name of the product.
        /// - `vendor` - The name of the vendor.
        /// </summary>
        public static Output<GetCseLogMappingVendorProductResult> Invoke(GetCseLogMappingVendorProductInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCseLogMappingVendorProductResult>("sumologic:index/getCseLogMappingVendorProduct:getCseLogMappingVendorProduct", args ?? new GetCseLogMappingVendorProductInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using SumoLogic = Pulumi.SumoLogic;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var webGateway = SumoLogic.GetCseLogMappingVendorProduct.Invoke(new()
        ///     {
        ///         Product = "Web Gateway",
        ///         Vendor = "McAfee",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// A Log mapping vendor product can be looked up by providing values of `product` and `vendor`
        /// Both `product` and `vendor` values are mandatory. If not provided an error will be generated.
        /// 
        /// ## Attributes reference
        /// 
        /// The following attributes are exported:
        /// 
        /// - `guid` - The internal GUID of the log mapping vendor product.
        /// - `product` - The name of the product.
        /// - `vendor` - The name of the vendor.
        /// </summary>
        public static Output<GetCseLogMappingVendorProductResult> Invoke(GetCseLogMappingVendorProductInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCseLogMappingVendorProductResult>("sumologic:index/getCseLogMappingVendorProduct:getCseLogMappingVendorProduct", args ?? new GetCseLogMappingVendorProductInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCseLogMappingVendorProductArgs : global::Pulumi.InvokeArgs
    {
        [Input("guid")]
        public string? Guid { get; set; }

        [Input("product", required: true)]
        public string Product { get; set; } = null!;

        [Input("vendor", required: true)]
        public string Vendor { get; set; } = null!;

        public GetCseLogMappingVendorProductArgs()
        {
        }
        public static new GetCseLogMappingVendorProductArgs Empty => new GetCseLogMappingVendorProductArgs();
    }

    public sealed class GetCseLogMappingVendorProductInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("guid")]
        public Input<string>? Guid { get; set; }

        [Input("product", required: true)]
        public Input<string> Product { get; set; } = null!;

        [Input("vendor", required: true)]
        public Input<string> Vendor { get; set; } = null!;

        public GetCseLogMappingVendorProductInvokeArgs()
        {
        }
        public static new GetCseLogMappingVendorProductInvokeArgs Empty => new GetCseLogMappingVendorProductInvokeArgs();
    }


    [OutputType]
    public sealed class GetCseLogMappingVendorProductResult
    {
        public readonly string Guid;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Product;
        public readonly string Vendor;

        [OutputConstructor]
        private GetCseLogMappingVendorProductResult(
            string guid,

            string id,

            string product,

            string vendor)
        {
            Guid = guid;
            Id = id;
            Product = product;
            Vendor = vendor;
        }
    }
}
