// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic
{
    /// <summary>
    /// Provides a [Sumologic Ingest Budget v2][1].
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using SumoLogic = Pulumi.SumoLogic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var budget = new SumoLogic.IngestBudgetV2("budget", new()
    ///     {
    ///         Action = "keepCollecting",
    ///         AuditThreshold = 85,
    ///         BudgetType = "dailyVolume",
    ///         CapacityBytes = 30000000000,
    ///         Description = "For testing purposes",
    ///         ResetTime = "00:00",
    ///         Scope = "_sourceCategory=*prod*nginx*",
    ///         Timezone = "Etc/UTC",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Ingest budgets can be imported using the budget ID, e.g.:
    /// 
    /// hcl
    /// 
    /// ```sh
    /// $ pulumi import sumologic:index/ingestBudgetV2:IngestBudgetV2 budget 00000000000123AB
    /// ```
    /// 
    /// [1]: https://help.sumologic.com/Beta/Metadata_Ingest_Budgets
    /// 
    /// [2]: https://en.wikipedia.org/wiki/Tz_database
    /// </summary>
    [SumoLogicResourceType("sumologic:index/ingestBudgetV2:IngestBudgetV2")]
    public partial class IngestBudgetV2 : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Action to take when ingest budget's capacity is reached. All actions are audited. Supported values are `stopCollecting` and `keepCollecting`.
        /// </summary>
        [Output("action")]
        public Output<string> Action { get; private set; } = null!;

        /// <summary>
        /// The threshold as a percentage of when an ingest budget's capacity usage is logged in the Audit Index.
        /// 
        /// The following attributes are exported:
        /// </summary>
        [Output("auditThreshold")]
        public Output<int?> AuditThreshold { get; private set; } = null!;

        /// <summary>
        /// The type of budget. Supported values are:  * `dailyVolume` * `minuteVolume`. Default value is `dailyVolume`.
        /// </summary>
        [Output("budgetType")]
        public Output<string?> BudgetType { get; private set; } = null!;

        /// <summary>
        /// Capacity of the ingest budget, in bytes. It takes a few minutes for Collectors to stop collecting when capacity is reached. We recommend setting a soft limit that is lower than your needed hard limit. The capacity bytes unit varies based on the budgetType field. For `dailyVolume` budgetType the capacity specified is in bytes/day whereas for `minuteVolume` budgetType its bytes/min.
        /// </summary>
        [Output("capacityBytes")]
        public Output<int> CapacityBytes { get; private set; } = null!;

        /// <summary>
        /// The description of the collector.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Display name of the ingest budget. This must be unique across all of the ingest budgets
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Reset time of the ingest budget in HH:MM format. Defaults to `00:00`
        /// </summary>
        [Output("resetTime")]
        public Output<string> ResetTime { get; private set; } = null!;

        /// <summary>
        /// A scope is a constraint that will be used to identify the messages on which budget needs to be applied. A scope is consists of key and value separated by =. The field must be enabled in the fields table.
        /// </summary>
        [Output("scope")]
        public Output<string> Scope { get; private set; } = null!;

        /// <summary>
        /// The time zone to use for this collector. The value follows the [tzdata](https://en.wikipedia.org/wiki/Tz_database) naming convention. Defaults to `Etc/UTC`
        /// </summary>
        [Output("timezone")]
        public Output<string> Timezone { get; private set; } = null!;


        /// <summary>
        /// Create a IngestBudgetV2 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IngestBudgetV2(string name, IngestBudgetV2Args args, CustomResourceOptions? options = null)
            : base("sumologic:index/ingestBudgetV2:IngestBudgetV2", name, args ?? new IngestBudgetV2Args(), MakeResourceOptions(options, ""))
        {
        }

        private IngestBudgetV2(string name, Input<string> id, IngestBudgetV2State? state = null, CustomResourceOptions? options = null)
            : base("sumologic:index/ingestBudgetV2:IngestBudgetV2", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IngestBudgetV2 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IngestBudgetV2 Get(string name, Input<string> id, IngestBudgetV2State? state = null, CustomResourceOptions? options = null)
        {
            return new IngestBudgetV2(name, id, state, options);
        }
    }

    public sealed class IngestBudgetV2Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action to take when ingest budget's capacity is reached. All actions are audited. Supported values are `stopCollecting` and `keepCollecting`.
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// The threshold as a percentage of when an ingest budget's capacity usage is logged in the Audit Index.
        /// 
        /// The following attributes are exported:
        /// </summary>
        [Input("auditThreshold")]
        public Input<int>? AuditThreshold { get; set; }

        /// <summary>
        /// The type of budget. Supported values are:  * `dailyVolume` * `minuteVolume`. Default value is `dailyVolume`.
        /// </summary>
        [Input("budgetType")]
        public Input<string>? BudgetType { get; set; }

        /// <summary>
        /// Capacity of the ingest budget, in bytes. It takes a few minutes for Collectors to stop collecting when capacity is reached. We recommend setting a soft limit that is lower than your needed hard limit. The capacity bytes unit varies based on the budgetType field. For `dailyVolume` budgetType the capacity specified is in bytes/day whereas for `minuteVolume` budgetType its bytes/min.
        /// </summary>
        [Input("capacityBytes", required: true)]
        public Input<int> CapacityBytes { get; set; } = null!;

        /// <summary>
        /// The description of the collector.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Display name of the ingest budget. This must be unique across all of the ingest budgets
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reset time of the ingest budget in HH:MM format. Defaults to `00:00`
        /// </summary>
        [Input("resetTime", required: true)]
        public Input<string> ResetTime { get; set; } = null!;

        /// <summary>
        /// A scope is a constraint that will be used to identify the messages on which budget needs to be applied. A scope is consists of key and value separated by =. The field must be enabled in the fields table.
        /// </summary>
        [Input("scope", required: true)]
        public Input<string> Scope { get; set; } = null!;

        /// <summary>
        /// The time zone to use for this collector. The value follows the [tzdata](https://en.wikipedia.org/wiki/Tz_database) naming convention. Defaults to `Etc/UTC`
        /// </summary>
        [Input("timezone", required: true)]
        public Input<string> Timezone { get; set; } = null!;

        public IngestBudgetV2Args()
        {
        }
        public static new IngestBudgetV2Args Empty => new IngestBudgetV2Args();
    }

    public sealed class IngestBudgetV2State : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action to take when ingest budget's capacity is reached. All actions are audited. Supported values are `stopCollecting` and `keepCollecting`.
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// The threshold as a percentage of when an ingest budget's capacity usage is logged in the Audit Index.
        /// 
        /// The following attributes are exported:
        /// </summary>
        [Input("auditThreshold")]
        public Input<int>? AuditThreshold { get; set; }

        /// <summary>
        /// The type of budget. Supported values are:  * `dailyVolume` * `minuteVolume`. Default value is `dailyVolume`.
        /// </summary>
        [Input("budgetType")]
        public Input<string>? BudgetType { get; set; }

        /// <summary>
        /// Capacity of the ingest budget, in bytes. It takes a few minutes for Collectors to stop collecting when capacity is reached. We recommend setting a soft limit that is lower than your needed hard limit. The capacity bytes unit varies based on the budgetType field. For `dailyVolume` budgetType the capacity specified is in bytes/day whereas for `minuteVolume` budgetType its bytes/min.
        /// </summary>
        [Input("capacityBytes")]
        public Input<int>? CapacityBytes { get; set; }

        /// <summary>
        /// The description of the collector.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Display name of the ingest budget. This must be unique across all of the ingest budgets
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reset time of the ingest budget in HH:MM format. Defaults to `00:00`
        /// </summary>
        [Input("resetTime")]
        public Input<string>? ResetTime { get; set; }

        /// <summary>
        /// A scope is a constraint that will be used to identify the messages on which budget needs to be applied. A scope is consists of key and value separated by =. The field must be enabled in the fields table.
        /// </summary>
        [Input("scope")]
        public Input<string>? Scope { get; set; }

        /// <summary>
        /// The time zone to use for this collector. The value follows the [tzdata](https://en.wikipedia.org/wiki/Tz_database) naming convention. Defaults to `Etc/UTC`
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public IngestBudgetV2State()
        {
        }
        public static new IngestBudgetV2State Empty => new IngestBudgetV2State();
    }
}
