// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.sumologic.inputs.AzureEventHubLogSourcePathAzureTagFilterTagArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AzureEventHubLogSourcePathAzureTagFilterArgs extends com.pulumi.resources.ResourceArgs {

    public static final AzureEventHubLogSourcePathAzureTagFilterArgs Empty = new AzureEventHubLogSourcePathAzureTagFilterArgs();

    /**
     * The namespace of the event hub.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return The namespace of the event hub.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    @Import(name="tags")
    private @Nullable Output<List<AzureEventHubLogSourcePathAzureTagFilterTagArgs>> tags;

    public Optional<Output<List<AzureEventHubLogSourcePathAzureTagFilterTagArgs>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private AzureEventHubLogSourcePathAzureTagFilterArgs() {}

    private AzureEventHubLogSourcePathAzureTagFilterArgs(AzureEventHubLogSourcePathAzureTagFilterArgs $) {
        this.namespace = $.namespace;
        this.tags = $.tags;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AzureEventHubLogSourcePathAzureTagFilterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AzureEventHubLogSourcePathAzureTagFilterArgs $;

        public Builder() {
            $ = new AzureEventHubLogSourcePathAzureTagFilterArgs();
        }

        public Builder(AzureEventHubLogSourcePathAzureTagFilterArgs defaults) {
            $ = new AzureEventHubLogSourcePathAzureTagFilterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param namespace The namespace of the event hub.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace The namespace of the event hub.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public Builder tags(@Nullable Output<List<AzureEventHubLogSourcePathAzureTagFilterTagArgs>> tags) {
            $.tags = tags;
            return this;
        }

        public Builder tags(List<AzureEventHubLogSourcePathAzureTagFilterTagArgs> tags) {
            return tags(Output.of(tags));
        }

        public Builder tags(AzureEventHubLogSourcePathAzureTagFilterTagArgs... tags) {
            return tags(List.of(tags));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public AzureEventHubLogSourcePathAzureTagFilterArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("AzureEventHubLogSourcePathAzureTagFilterArgs", "type");
            }
            return $;
        }
    }

}
