// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs extends com.pulumi.resources.ResourceArgs {

    public static final MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs Empty = new MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs();

    @Import(name="minAnomalyCount")
    private @Nullable Output<Integer> minAnomalyCount;

    public Optional<Output<Integer>> minAnomalyCount() {
        return Optional.ofNullable(this.minAnomalyCount);
    }

    @Import(name="sensitivity")
    private @Nullable Output<Double> sensitivity;

    public Optional<Output<Double>> sensitivity() {
        return Optional.ofNullable(this.sensitivity);
    }

    @Import(name="timeRange", required=true)
    private Output<String> timeRange;

    public Output<String> timeRange() {
        return this.timeRange;
    }

    private MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs() {}

    private MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs(MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs $) {
        this.minAnomalyCount = $.minAnomalyCount;
        this.sensitivity = $.sensitivity;
        this.timeRange = $.timeRange;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs $;

        public Builder() {
            $ = new MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs();
        }

        public Builder(MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs defaults) {
            $ = new MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs(Objects.requireNonNull(defaults));
        }

        public Builder minAnomalyCount(@Nullable Output<Integer> minAnomalyCount) {
            $.minAnomalyCount = minAnomalyCount;
            return this;
        }

        public Builder minAnomalyCount(Integer minAnomalyCount) {
            return minAnomalyCount(Output.of(minAnomalyCount));
        }

        public Builder sensitivity(@Nullable Output<Double> sensitivity) {
            $.sensitivity = sensitivity;
            return this;
        }

        public Builder sensitivity(Double sensitivity) {
            return sensitivity(Output.of(sensitivity));
        }

        public Builder timeRange(Output<String> timeRange) {
            $.timeRange = timeRange;
            return this;
        }

        public Builder timeRange(String timeRange) {
            return timeRange(Output.of(timeRange));
        }

        public MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs build() {
            if ($.timeRange == null) {
                throw new MissingRequiredPropertyException("MonitorTriggerConditionsMetricsAnomalyConditionCriticalArgs", "timeRange");
            }
            return $;
        }
    }

}
