// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sumologic.inputs.MonitorTriggerConditionsLogsStaticConditionCriticalArgs;
import com.pulumi.sumologic.inputs.MonitorTriggerConditionsLogsStaticConditionWarningArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MonitorTriggerConditionsLogsStaticConditionArgs extends com.pulumi.resources.ResourceArgs {

    public static final MonitorTriggerConditionsLogsStaticConditionArgs Empty = new MonitorTriggerConditionsLogsStaticConditionArgs();

    @Import(name="critical")
    private @Nullable Output<MonitorTriggerConditionsLogsStaticConditionCriticalArgs> critical;

    public Optional<Output<MonitorTriggerConditionsLogsStaticConditionCriticalArgs>> critical() {
        return Optional.ofNullable(this.critical);
    }

    @Import(name="field")
    private @Nullable Output<String> field;

    public Optional<Output<String>> field() {
        return Optional.ofNullable(this.field);
    }

    @Import(name="warning")
    private @Nullable Output<MonitorTriggerConditionsLogsStaticConditionWarningArgs> warning;

    public Optional<Output<MonitorTriggerConditionsLogsStaticConditionWarningArgs>> warning() {
        return Optional.ofNullable(this.warning);
    }

    private MonitorTriggerConditionsLogsStaticConditionArgs() {}

    private MonitorTriggerConditionsLogsStaticConditionArgs(MonitorTriggerConditionsLogsStaticConditionArgs $) {
        this.critical = $.critical;
        this.field = $.field;
        this.warning = $.warning;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MonitorTriggerConditionsLogsStaticConditionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MonitorTriggerConditionsLogsStaticConditionArgs $;

        public Builder() {
            $ = new MonitorTriggerConditionsLogsStaticConditionArgs();
        }

        public Builder(MonitorTriggerConditionsLogsStaticConditionArgs defaults) {
            $ = new MonitorTriggerConditionsLogsStaticConditionArgs(Objects.requireNonNull(defaults));
        }

        public Builder critical(@Nullable Output<MonitorTriggerConditionsLogsStaticConditionCriticalArgs> critical) {
            $.critical = critical;
            return this;
        }

        public Builder critical(MonitorTriggerConditionsLogsStaticConditionCriticalArgs critical) {
            return critical(Output.of(critical));
        }

        public Builder field(@Nullable Output<String> field) {
            $.field = field;
            return this;
        }

        public Builder field(String field) {
            return field(Output.of(field));
        }

        public Builder warning(@Nullable Output<MonitorTriggerConditionsLogsStaticConditionWarningArgs> warning) {
            $.warning = warning;
            return this;
        }

        public Builder warning(MonitorTriggerConditionsLogsStaticConditionWarningArgs warning) {
            return warning(Output.of(warning));
        }

        public MonitorTriggerConditionsLogsStaticConditionArgs build() {
            return $;
        }
    }

}
