// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange {
    private String rangeName;

    private DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange() {}
    public String rangeName() {
        return this.rangeName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String rangeName;
        public Builder() {}
        public Builder(DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.rangeName = defaults.rangeName;
        }

        @CustomType.Setter
        public Builder rangeName(String rangeName) {
            if (rangeName == null) {
              throw new MissingRequiredPropertyException("DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange", "rangeName");
            }
            this.rangeName = rangeName;
            return this;
        }
        public DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange build() {
            final var _resultValue = new DashboardPanelTracesListPanelTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange();
            _resultValue.rangeName = rangeName;
            return _resultValue;
        }
    }
}
