// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DashboardPanelSumoSearchPanelLinkedDashboard {
    private String id;
    private @Nullable Boolean includeTimeRange;
    private @Nullable Boolean includeVariables;
    private @Nullable String relativePath;

    private DashboardPanelSumoSearchPanelLinkedDashboard() {}
    public String id() {
        return this.id;
    }
    public Optional<Boolean> includeTimeRange() {
        return Optional.ofNullable(this.includeTimeRange);
    }
    public Optional<Boolean> includeVariables() {
        return Optional.ofNullable(this.includeVariables);
    }
    public Optional<String> relativePath() {
        return Optional.ofNullable(this.relativePath);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardPanelSumoSearchPanelLinkedDashboard defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private @Nullable Boolean includeTimeRange;
        private @Nullable Boolean includeVariables;
        private @Nullable String relativePath;
        public Builder() {}
        public Builder(DashboardPanelSumoSearchPanelLinkedDashboard defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.includeTimeRange = defaults.includeTimeRange;
    	      this.includeVariables = defaults.includeVariables;
    	      this.relativePath = defaults.relativePath;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder includeTimeRange(@Nullable Boolean includeTimeRange) {
            this.includeTimeRange = includeTimeRange;
            return this;
        }
        @CustomType.Setter
        public Builder includeVariables(@Nullable Boolean includeVariables) {
            this.includeVariables = includeVariables;
            return this;
        }
        @CustomType.Setter
        public Builder relativePath(@Nullable String relativePath) {
            this.relativePath = relativePath;
            return this;
        }
        public DashboardPanelSumoSearchPanelLinkedDashboard build() {
            final var _resultValue = new DashboardPanelSumoSearchPanelLinkedDashboard();
            _resultValue.id = id;
            _resultValue.includeTimeRange = includeTimeRange;
            _resultValue.includeVariables = includeVariables;
            _resultValue.relativePath = relativePath;
            return _resultValue;
        }
    }
}
