// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GcpMetricsSourcePathCustomService {
    /**
     * @return List of metric type prefixes. Eg: `[&#34;compute.googleapis.com/instance/&#34;,&#34;compute.googleapis.com/guest/&#34;]`
     * 
     */
    private final @Nullable List<String> prefixes;
    /**
     * @return Name of the custom service you want to define.
     * 
     */
    private final @Nullable String serviceName;

    @CustomType.Constructor
    private GcpMetricsSourcePathCustomService(
        @CustomType.Parameter("prefixes") @Nullable List<String> prefixes,
        @CustomType.Parameter("serviceName") @Nullable String serviceName) {
        this.prefixes = prefixes;
        this.serviceName = serviceName;
    }

    /**
     * @return List of metric type prefixes. Eg: `[&#34;compute.googleapis.com/instance/&#34;,&#34;compute.googleapis.com/guest/&#34;]`
     * 
     */
    public List<String> prefixes() {
        return this.prefixes == null ? List.of() : this.prefixes;
    }
    /**
     * @return Name of the custom service you want to define.
     * 
     */
    public Optional<String> serviceName() {
        return Optional.ofNullable(this.serviceName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GcpMetricsSourcePathCustomService defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<String> prefixes;
        private @Nullable String serviceName;

        public Builder() {
    	      // Empty
        }

        public Builder(GcpMetricsSourcePathCustomService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.prefixes = defaults.prefixes;
    	      this.serviceName = defaults.serviceName;
        }

        public Builder prefixes(@Nullable List<String> prefixes) {
            this.prefixes = prefixes;
            return this;
        }
        public Builder prefixes(String... prefixes) {
            return prefixes(List.of(prefixes));
        }
        public Builder serviceName(@Nullable String serviceName) {
            this.serviceName = serviceName;
            return this;
        }        public GcpMetricsSourcePathCustomService build() {
            return new GcpMetricsSourcePathCustomService(prefixes, serviceName);
        }
    }
}
