// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class KineisLogSourcePath {
    /**
     * @return The name of the bucket. This is needed if using type `KinesisLogPath`.
     * 
     */
    private final @Nullable String bucketName;
    /**
     * @return The path to the data. This is needed if using type `KinesisLogPath`. For Kinesis log source, it must includes `http-endpoint-failed/`.
     * 
     */
    private final @Nullable String pathExpression;
    /**
     * @return The Time interval in milliseconds of scans for new data. The default is 300000 and the minimum value is 1000 milliseconds.
     * 
     */
    private final @Nullable Integer scanInterval;
    /**
     * @return Must be either `KinesisLogPath` or `NoPathExpression`
     * 
     */
    private final String type;

    @CustomType.Constructor
    private KineisLogSourcePath(
        @CustomType.Parameter("bucketName") @Nullable String bucketName,
        @CustomType.Parameter("pathExpression") @Nullable String pathExpression,
        @CustomType.Parameter("scanInterval") @Nullable Integer scanInterval,
        @CustomType.Parameter("type") String type) {
        this.bucketName = bucketName;
        this.pathExpression = pathExpression;
        this.scanInterval = scanInterval;
        this.type = type;
    }

    /**
     * @return The name of the bucket. This is needed if using type `KinesisLogPath`.
     * 
     */
    public Optional<String> bucketName() {
        return Optional.ofNullable(this.bucketName);
    }
    /**
     * @return The path to the data. This is needed if using type `KinesisLogPath`. For Kinesis log source, it must includes `http-endpoint-failed/`.
     * 
     */
    public Optional<String> pathExpression() {
        return Optional.ofNullable(this.pathExpression);
    }
    /**
     * @return The Time interval in milliseconds of scans for new data. The default is 300000 and the minimum value is 1000 milliseconds.
     * 
     */
    public Optional<Integer> scanInterval() {
        return Optional.ofNullable(this.scanInterval);
    }
    /**
     * @return Must be either `KinesisLogPath` or `NoPathExpression`
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KineisLogSourcePath defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String bucketName;
        private @Nullable String pathExpression;
        private @Nullable Integer scanInterval;
        private String type;

        public Builder() {
    	      // Empty
        }

        public Builder(KineisLogSourcePath defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bucketName = defaults.bucketName;
    	      this.pathExpression = defaults.pathExpression;
    	      this.scanInterval = defaults.scanInterval;
    	      this.type = defaults.type;
        }

        public Builder bucketName(@Nullable String bucketName) {
            this.bucketName = bucketName;
            return this;
        }
        public Builder pathExpression(@Nullable String pathExpression) {
            this.pathExpression = pathExpression;
            return this;
        }
        public Builder scanInterval(@Nullable Integer scanInterval) {
            this.scanInterval = scanInterval;
            return this;
        }
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }        public KineisLogSourcePath build() {
            return new KineisLogSourcePath(bucketName, pathExpression, scanInterval, type);
        }
    }
}
