// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.sumologic.outputs.LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromEpochTimeRange;
import com.pulumi.sumologic.outputs.LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromIso8601TimeRange;
import com.pulumi.sumologic.outputs.LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange;
import com.pulumi.sumologic.outputs.LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromRelativeTimeRange;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom {
    /**
     * @return (Block List, Optional) Time since the epoch.
     * 
     */
    private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromEpochTimeRange epochTimeRange;
    /**
     * @return (Block List, Optional) Time in ISO 8601 format.
     * 
     */
    private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromIso8601TimeRange iso8601TimeRange;
    /**
     * @return (Block List, Optional) Time in literal format.
     * 
     */
    private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange literalTimeRange;
    /**
     * @return (Block List, Optional) Time in relative format.
     * 
     */
    private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromRelativeTimeRange relativeTimeRange;

    private LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom() {}
    /**
     * @return (Block List, Optional) Time since the epoch.
     * 
     */
    public Optional<LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromEpochTimeRange> epochTimeRange() {
        return Optional.ofNullable(this.epochTimeRange);
    }
    /**
     * @return (Block List, Optional) Time in ISO 8601 format.
     * 
     */
    public Optional<LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromIso8601TimeRange> iso8601TimeRange() {
        return Optional.ofNullable(this.iso8601TimeRange);
    }
    /**
     * @return (Block List, Optional) Time in literal format.
     * 
     */
    public Optional<LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange> literalTimeRange() {
        return Optional.ofNullable(this.literalTimeRange);
    }
    /**
     * @return (Block List, Optional) Time in relative format.
     * 
     */
    public Optional<LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromRelativeTimeRange> relativeTimeRange() {
        return Optional.ofNullable(this.relativeTimeRange);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromEpochTimeRange epochTimeRange;
        private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromIso8601TimeRange iso8601TimeRange;
        private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange literalTimeRange;
        private @Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromRelativeTimeRange relativeTimeRange;
        public Builder() {}
        public Builder(LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.epochTimeRange = defaults.epochTimeRange;
    	      this.iso8601TimeRange = defaults.iso8601TimeRange;
    	      this.literalTimeRange = defaults.literalTimeRange;
    	      this.relativeTimeRange = defaults.relativeTimeRange;
        }

        @CustomType.Setter
        public Builder epochTimeRange(@Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromEpochTimeRange epochTimeRange) {
            this.epochTimeRange = epochTimeRange;
            return this;
        }
        @CustomType.Setter
        public Builder iso8601TimeRange(@Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromIso8601TimeRange iso8601TimeRange) {
            this.iso8601TimeRange = iso8601TimeRange;
            return this;
        }
        @CustomType.Setter
        public Builder literalTimeRange(@Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromLiteralTimeRange literalTimeRange) {
            this.literalTimeRange = literalTimeRange;
            return this;
        }
        @CustomType.Setter
        public Builder relativeTimeRange(@Nullable LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFromRelativeTimeRange relativeTimeRange) {
            this.relativeTimeRange = relativeTimeRange;
            return this;
        }
        public LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom build() {
            final var o = new LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeFrom();
            o.epochTimeRange = epochTimeRange;
            o.iso8601TimeRange = iso8601TimeRange;
            o.literalTimeRange = literalTimeRange;
            o.relativeTimeRange = relativeTimeRange;
            return o;
        }
    }
}
