// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.sumologic.outputs.SloIndicatorRequestBasedEvaluation;
import com.pulumi.sumologic.outputs.SloIndicatorWindowBasedEvaluation;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SloIndicator {
    private final @Nullable SloIndicatorRequestBasedEvaluation requestBasedEvaluation;
    private final @Nullable SloIndicatorWindowBasedEvaluation windowBasedEvaluation;

    @CustomType.Constructor
    private SloIndicator(
        @CustomType.Parameter("requestBasedEvaluation") @Nullable SloIndicatorRequestBasedEvaluation requestBasedEvaluation,
        @CustomType.Parameter("windowBasedEvaluation") @Nullable SloIndicatorWindowBasedEvaluation windowBasedEvaluation) {
        this.requestBasedEvaluation = requestBasedEvaluation;
        this.windowBasedEvaluation = windowBasedEvaluation;
    }

    public Optional<SloIndicatorRequestBasedEvaluation> requestBasedEvaluation() {
        return Optional.ofNullable(this.requestBasedEvaluation);
    }
    public Optional<SloIndicatorWindowBasedEvaluation> windowBasedEvaluation() {
        return Optional.ofNullable(this.windowBasedEvaluation);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SloIndicator defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable SloIndicatorRequestBasedEvaluation requestBasedEvaluation;
        private @Nullable SloIndicatorWindowBasedEvaluation windowBasedEvaluation;

        public Builder() {
    	      // Empty
        }

        public Builder(SloIndicator defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.requestBasedEvaluation = defaults.requestBasedEvaluation;
    	      this.windowBasedEvaluation = defaults.windowBasedEvaluation;
        }

        public Builder requestBasedEvaluation(@Nullable SloIndicatorRequestBasedEvaluation requestBasedEvaluation) {
            this.requestBasedEvaluation = requestBasedEvaluation;
            return this;
        }
        public Builder windowBasedEvaluation(@Nullable SloIndicatorWindowBasedEvaluation windowBasedEvaluation) {
            this.windowBasedEvaluation = windowBasedEvaluation;
            return this;
        }        public SloIndicator build() {
            return new SloIndicator(requestBasedEvaluation, windowBasedEvaluation);
        }
    }
}
