// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("sumologic");

export let accessId: string | undefined = __config.get("accessId");
export let accessKey: string | undefined = __config.get("accessKey");
export let baseUrl: string | undefined = __config.get("baseUrl") || utilities.getEnv("SUMOLOGIC_BASE_URL");
export let environment: string | undefined = __config.get("environment") || utilities.getEnv("SUMOLOGIC_ENVIRONMENT");
