// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sumologic.ContentArgs;
import com.pulumi.sumologic.Utilities;
import com.pulumi.sumologic.inputs.ContentState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sumologic.SumologicFunctions;
 * import com.pulumi.sumologic.inputs.GetPersonalFolderArgs;
 * import com.pulumi.sumologic.Content;
 * import com.pulumi.sumologic.ContentArgs;
 * import static com.pulumi.codegen.internal.Serialization.*;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App }{{@code
 *     public static void main(String[] args) }{{@code
 *         Pulumi.run(App::stack);
 *     }}{@code
 * 
 *     public static void stack(Context ctx) }{{@code
 *         final var personalFolder = SumologicFunctions.getPersonalFolder(GetPersonalFolderArgs.builder()
 *             .build());
 * 
 *         var test = new Content("test", ContentArgs.builder()
 *             .parentId(personalFolder.id())
 *             .config(serializeJson(
 *                 jsonObject(
 *                     jsonProperty("type", "SavedSearchWithScheduleSyncDefinition"),
 *                     jsonProperty("name", "test-333"),
 *                     jsonProperty("search", jsonObject(
 *                         jsonProperty("queryText", "\"warn\""),
 *                         jsonProperty("defaultTimeRange", "-15m"),
 *                         jsonProperty("byReceiptTime", false),
 *                         jsonProperty("viewName", ""),
 *                         jsonProperty("viewStartTime", "1970-01-01T00:00:00Z"),
 *                         jsonProperty("queryParameters", jsonArray(
 *                         )),
 *                         jsonProperty("parsingMode", "Manual")
 *                     )),
 *                     jsonProperty("searchSchedule", jsonObject(
 *                         jsonProperty("cronExpression", "0 0 * * * ? *"),
 *                         jsonProperty("displayableTimeRange", "-10m"),
 *                         jsonProperty("parseableTimeRange", jsonObject(
 *                             jsonProperty("type", "BeginBoundedTimeRange"),
 *                             jsonProperty("from", jsonObject(
 *                                 jsonProperty("type", "RelativeTimeRangeBoundary"),
 *                                 jsonProperty("relativeTime", "-50m")
 *                             )),
 *                             jsonProperty("to", null)
 *                         )),
 *                         jsonProperty("timeZone", "America/Los_Angeles"),
 *                         jsonProperty("threshold", jsonObject(
 *                             jsonProperty("operator", "gt"),
 *                             jsonProperty("count", 0)
 *                         )),
 *                         jsonProperty("notification", jsonObject(
 *                             jsonProperty("taskType", "EmailSearchNotificationSyncDefinition"),
 *                             jsonProperty("toList", jsonArray("ops}{@literal @}{@code acme.org")),
 *                             jsonProperty("subjectTemplate", "Search Results: }{{{@code Name}}}{@code "),
 *                             jsonProperty("includeQuery", true),
 *                             jsonProperty("includeResultSet", true),
 *                             jsonProperty("includeHistogram", false),
 *                             jsonProperty("includeCsvAttachment", false)
 *                         )),
 *                         jsonProperty("scheduleType", "1Hour"),
 *                         jsonProperty("muteErrorEmails", false),
 *                         jsonProperty("parameters", jsonArray(
 *                         ))
 *                     )),
 *                     jsonProperty("description", "Runs every hour with timerange of 15m and sends email notifications")
 *                 )))
 *             .build());
 * 
 *     }}{@code
 * }}{@code
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Attributes reference
 * 
 * The following attributes are exported:
 * 
 * - `id` - Unique identifier for the content item.
 * 
 * [1]: https://help.sumologic.com/APIs/Content-Management-API
 * 
 */
@ResourceType(type="sumologic:index/content:Content")
public class Content extends com.pulumi.resources.CustomResource {
    /**
     * JSON block for the content to import. NOTE: Updating the name will create a new object and leave a untracked content item (delete the existing content item and create a new content item if you want to update the name).
     * 
     */
    @Export(name="config", refs={String.class}, tree="[0]")
    private Output<String> config;

    /**
     * @return JSON block for the content to import. NOTE: Updating the name will create a new object and leave a untracked content item (delete the existing content item and create a new content item if you want to update the name).
     * 
     */
    public Output<String> config() {
        return this.config;
    }
    /**
     * The identifier of the folder to import into. Identifiers from the Library in the Sumo user interface are provided in decimal format which is incompatible with this provider. The identifier needs to be in hexadecimal format.
     * 
     */
    @Export(name="parentId", refs={String.class}, tree="[0]")
    private Output<String> parentId;

    /**
     * @return The identifier of the folder to import into. Identifiers from the Library in the Sumo user interface are provided in decimal format which is incompatible with this provider. The identifier needs to be in hexadecimal format.
     * 
     */
    public Output<String> parentId() {
        return this.parentId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Content(java.lang.String name) {
        this(name, ContentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Content(java.lang.String name, ContentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Content(java.lang.String name, ContentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/content:Content", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Content(java.lang.String name, Output<java.lang.String> id, @Nullable ContentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/content:Content", name, state, makeResourceOptions(options, id), false);
    }

    private static ContentArgs makeArgs(ContentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ContentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Content get(java.lang.String name, Output<java.lang.String> id, @Nullable ContentState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Content(name, id, state, options);
    }
}
