// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sumologic.CseInventoryEntityGroupConfigurationArgs;
import com.pulumi.sumologic.Utilities;
import com.pulumi.sumologic.inputs.CseInventoryEntityGroupConfigurationState;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sumologic.CseInventoryEntityGroupConfiguration;
 * import com.pulumi.sumologic.CseInventoryEntityGroupConfigurationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var inventoryEntityGroupConfiguration = new CseInventoryEntityGroupConfiguration(&#34;inventoryEntityGroupConfiguration&#34;, CseInventoryEntityGroupConfigurationArgs.builder()        
 *             .criticality(&#34;HIGH&#34;)
 *             .description(&#34;Inventory entity group description&#34;)
 *             .group(&#34;admin&#34;)
 *             .inventorySource(&#34;Active Directory&#34;)
 *             .inventoryType(&#34;user&#34;)
 *             .suppressed(false)
 *             .tags(&#34;tag&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Inventory Entity Group Configuration can be imported using the field id, e.g.hcl
 * 
 * ```sh
 *  $ pulumi import sumologic:index/cseInventoryEntityGroupConfiguration:CseInventoryEntityGroupConfiguration inventory_entity_group_configuration id
 * ```
 * 
 */
@ResourceType(type="sumologic:index/cseInventoryEntityGroupConfiguration:CseInventoryEntityGroupConfiguration")
public class CseInventoryEntityGroupConfiguration extends com.pulumi.resources.CustomResource {
    /**
     * The entity group configuration criticality Examples: &#34;HIGH&#34;, &#34;CRITICALITY&#34;.
     * 
     */
    @Export(name="criticality", type=String.class, parameters={})
    private Output</* @Nullable */ String> criticality;

    /**
     * @return The entity group configuration criticality Examples: &#34;HIGH&#34;, &#34;CRITICALITY&#34;.
     * 
     */
    public Output<Optional<String>> criticality() {
        return Codegen.optional(this.criticality);
    }
    /**
     * The entity group configuration description.
     * 
     */
    @Export(name="description", type=String.class, parameters={})
    private Output</* @Nullable */ String> description;

    /**
     * @return The entity group configuration description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The entity group configuration inventory group.
     * 
     */
    @Export(name="group", type=String.class, parameters={})
    private Output</* @Nullable */ String> group;

    /**
     * @return The entity group configuration inventory group.
     * 
     */
    public Output<Optional<String>> group() {
        return Codegen.optional(this.group);
    }
    /**
     * The inventory source Examples: &#34;Active Directory&#34;, &#34;Okta&#34;.
     * 
     */
    @Export(name="inventorySource", type=String.class, parameters={})
    private Output<String> inventorySource;

    /**
     * @return The inventory source Examples: &#34;Active Directory&#34;, &#34;Okta&#34;.
     * 
     */
    public Output<String> inventorySource() {
        return this.inventorySource;
    }
    /**
     * The inventory type Examples: &#34;computer&#34;, &#34;user&#34;.
     * 
     */
    @Export(name="inventoryType", type=String.class, parameters={})
    private Output<String> inventoryType;

    /**
     * @return The inventory type Examples: &#34;computer&#34;, &#34;user&#34;.
     * 
     */
    public Output<String> inventoryType() {
        return this.inventoryType;
    }
    /**
     * The entity group configuration name.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The entity group configuration name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    @Export(name="suppressed", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> suppressed;

    public Output<Optional<Boolean>> suppressed() {
        return Codegen.optional(this.suppressed);
    }
    /**
     * The entity group configuration tags list.
     * 
     * The following attributes are exported:
     * 
     */
    @Export(name="tags", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return The entity group configuration tags list.
     * 
     * The following attributes are exported:
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CseInventoryEntityGroupConfiguration(String name) {
        this(name, CseInventoryEntityGroupConfigurationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CseInventoryEntityGroupConfiguration(String name, CseInventoryEntityGroupConfigurationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CseInventoryEntityGroupConfiguration(String name, CseInventoryEntityGroupConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/cseInventoryEntityGroupConfiguration:CseInventoryEntityGroupConfiguration", name, args == null ? CseInventoryEntityGroupConfigurationArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private CseInventoryEntityGroupConfiguration(String name, Output<String> id, @Nullable CseInventoryEntityGroupConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/cseInventoryEntityGroupConfiguration:CseInventoryEntityGroupConfiguration", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CseInventoryEntityGroupConfiguration get(String name, Output<String> id, @Nullable CseInventoryEntityGroupConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CseInventoryEntityGroupConfiguration(name, id, state, options);
    }
}
