// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sumologic;

import com.pulumi.core.Alias;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sumologic.KinesisLogSourceArgs;
import com.pulumi.sumologic.Utilities;
import com.pulumi.sumologic.inputs.KinesisLogSourceState;
import com.pulumi.sumologic.outputs.KinesisLogSourceAuthentication;
import com.pulumi.sumologic.outputs.KinesisLogSourceDefaultDateFormat;
import com.pulumi.sumologic.outputs.KinesisLogSourceFilter;
import com.pulumi.sumologic.outputs.KinesisLogSourcePath;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a [Sumologic Kinesis Log source](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Amazon-Web-Services/AWS_Kinesis_Firehose_for_Logs_Source). This source is used to ingest log via Kinesis Firehose from AWS.
 * 
 * __IMPORTANT:__ The AWS credentials are stored in plain-text in the state. This is a potential security issue.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sumologic.Collector;
 * import com.pulumi.sumologic.CollectorArgs;
 * import com.pulumi.sumologic.KinesisLogSource;
 * import com.pulumi.sumologic.KinesisLogSourceArgs;
 * import com.pulumi.sumologic.inputs.KinesisLogSourceAuthenticationArgs;
 * import com.pulumi.sumologic.inputs.KinesisLogSourcePathArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var collector = new Collector("collector", CollectorArgs.builder()
 *             .name("my-collector")
 *             .description("Just testing this")
 *             .build());
 * 
 *         var kinesisLogAccessKey = new KinesisLogSource("kinesisLogAccessKey", KinesisLogSourceArgs.builder()
 *             .name("Kinesis Log")
 *             .description("Description for Kinesis Log Source")
 *             .category("prod/kinesis/log")
 *             .contentType("KinesisLog")
 *             .collectorId(collector.id())
 *             .authentication(KinesisLogSourceAuthenticationArgs.builder()
 *                 .type("S3BucketAuthentication")
 *                 .accessKey("someKey")
 *                 .secretKey("******")
 *                 .build())
 *             .path(KinesisLogSourcePathArgs.builder()
 *                 .type("KinesisLogPath")
 *                 .bucketName("testBucket")
 *                 .pathExpression("http-endpoint-failed/*")
 *                 .scanInterval(30000)
 *                 .build())
 *             .build());
 * 
 *         var kinesisLogRoleArn = new KinesisLogSource("kinesisLogRoleArn", KinesisLogSourceArgs.builder()
 *             .name("Kinesis Log")
 *             .description("Description for Kinesis Log Source")
 *             .category("prod/kinesis/log")
 *             .contentType("KinesisLog")
 *             .collectorId(collector.id())
 *             .authentication(KinesisLogSourceAuthenticationArgs.builder()
 *                 .type("AWSRoleBasedAuthentication")
 *                 .roleArn("arn:aws:iam::604066827510:role/cw-role-SumoRole-4AOLS73TGKYI")
 *                 .build())
 *             .path(KinesisLogSourcePathArgs.builder()
 *                 .type("KinesisLogPath")
 *                 .bucketName("testBucket")
 *                 .pathExpression("http-endpoint-failed/*")
 *                 .scanInterval(30000)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * Kinesis Log sources can be imported using the collector and source IDs (`collector/source`), e.g.:
 * 
 * hcl
 * 
 * ```sh
 * $ pulumi import sumologic:index/kinesisLogSource:KinesisLogSource test 123/456
 * ```
 * 
 * HTTP sources can be imported using the collector name and source name (`collectorName/sourceName`), e.g.:
 * 
 * hcl
 * 
 * ```sh
 * $ pulumi import sumologic:index/kinesisLogSource:KinesisLogSource test my-test-collector/my-test-source
 * ```
 * 
 * [1]: https://help.sumologic.com/Send_Data/Sources/03Use_JSON_to_Configure_Sources/JSON_Parameters_for_Hosted_Sources
 * 
 * [2]: https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Amazon-Web-Services/AWS_Kinesis_Firehose_for_Logs_Source
 * 
 */
@ResourceType(type="sumologic:index/kinesisLogSource:KinesisLogSource")
public class KinesisLogSource extends com.pulumi.resources.CustomResource {
    /**
     * Authentication details for connecting to the S3 bucket.
     * 
     */
    @Export(name="authentication", refs={KinesisLogSourceAuthentication.class}, tree="[0]")
    private Output</* @Nullable */ KinesisLogSourceAuthentication> authentication;

    /**
     * @return Authentication details for connecting to the S3 bucket.
     * 
     */
    public Output<Optional<KinesisLogSourceAuthentication>> authentication() {
        return Codegen.optional(this.authentication);
    }
    @Export(name="automaticDateParsing", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> automaticDateParsing;

    public Output<Optional<Boolean>> automaticDateParsing() {
        return Codegen.optional(this.automaticDateParsing);
    }
    @Export(name="category", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> category;

    public Output<Optional<String>> category() {
        return Codegen.optional(this.category);
    }
    @Export(name="collectorId", refs={Integer.class}, tree="[0]")
    private Output<Integer> collectorId;

    public Output<Integer> collectorId() {
        return this.collectorId;
    }
    /**
     * The content-type of the collected data. Details can be found in the [Sumologic documentation for hosted sources](https://help.sumologic.com/Send_Data/Sources/03Use_JSON_to_Configure_Sources/JSON_Parameters_for_Hosted_Sources).
     * 
     */
    @Export(name="contentType", refs={String.class}, tree="[0]")
    private Output<String> contentType;

    /**
     * @return The content-type of the collected data. Details can be found in the [Sumologic documentation for hosted sources](https://help.sumologic.com/Send_Data/Sources/03Use_JSON_to_Configure_Sources/JSON_Parameters_for_Hosted_Sources).
     * 
     */
    public Output<String> contentType() {
        return this.contentType;
    }
    @Export(name="cutoffRelativeTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cutoffRelativeTime;

    public Output<Optional<String>> cutoffRelativeTime() {
        return Codegen.optional(this.cutoffRelativeTime);
    }
    @Export(name="cutoffTimestamp", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> cutoffTimestamp;

    public Output<Optional<Integer>> cutoffTimestamp() {
        return Codegen.optional(this.cutoffTimestamp);
    }
    @Export(name="defaultDateFormats", refs={List.class,KinesisLogSourceDefaultDateFormat.class}, tree="[0,1]")
    private Output</* @Nullable */ List<KinesisLogSourceDefaultDateFormat>> defaultDateFormats;

    public Output<Optional<List<KinesisLogSourceDefaultDateFormat>>> defaultDateFormats() {
        return Codegen.optional(this.defaultDateFormats);
    }
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    @Export(name="fields", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> fields;

    public Output<Optional<Map<String,String>>> fields() {
        return Codegen.optional(this.fields);
    }
    @Export(name="filters", refs={List.class,KinesisLogSourceFilter.class}, tree="[0,1]")
    private Output</* @Nullable */ List<KinesisLogSourceFilter>> filters;

    public Output<Optional<List<KinesisLogSourceFilter>>> filters() {
        return Codegen.optional(this.filters);
    }
    @Export(name="forceTimezone", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> forceTimezone;

    public Output<Optional<Boolean>> forceTimezone() {
        return Codegen.optional(this.forceTimezone);
    }
    @Export(name="hashAlgorithm", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> hashAlgorithm;

    public Output<Optional<String>> hashAlgorithm() {
        return Codegen.optional(this.hashAlgorithm);
    }
    @Export(name="hostName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> hostName;

    public Output<Optional<String>> hostName() {
        return Codegen.optional(this.hostName);
    }
    @Export(name="manualPrefixRegexp", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> manualPrefixRegexp;

    public Output<Optional<String>> manualPrefixRegexp() {
        return Codegen.optional(this.manualPrefixRegexp);
    }
    @Export(name="messagePerRequest", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> messagePerRequest;

    public Output<Optional<Boolean>> messagePerRequest() {
        return Codegen.optional(this.messagePerRequest);
    }
    @Export(name="multilineProcessingEnabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> multilineProcessingEnabled;

    public Output<Optional<Boolean>> multilineProcessingEnabled() {
        return Codegen.optional(this.multilineProcessingEnabled);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    /**
     * The location of S3 bucket for failed Kinesis log data.
     * 
     */
    @Export(name="path", refs={KinesisLogSourcePath.class}, tree="[0]")
    private Output</* @Nullable */ KinesisLogSourcePath> path;

    /**
     * @return The location of S3 bucket for failed Kinesis log data.
     * 
     */
    public Output<Optional<KinesisLogSourcePath>> path() {
        return Codegen.optional(this.path);
    }
    @Export(name="timezone", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> timezone;

    public Output<Optional<String>> timezone() {
        return Codegen.optional(this.timezone);
    }
    /**
     * The HTTP endpoint to be used while creating Kinesis Firehose on AWS.
     * 
     */
    @Export(name="url", refs={String.class}, tree="[0]")
    private Output<String> url;

    /**
     * @return The HTTP endpoint to be used while creating Kinesis Firehose on AWS.
     * 
     */
    public Output<String> url() {
        return this.url;
    }
    @Export(name="useAutolineMatching", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> useAutolineMatching;

    public Output<Optional<Boolean>> useAutolineMatching() {
        return Codegen.optional(this.useAutolineMatching);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public KinesisLogSource(java.lang.String name) {
        this(name, KinesisLogSourceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public KinesisLogSource(java.lang.String name, KinesisLogSourceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public KinesisLogSource(java.lang.String name, KinesisLogSourceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/kinesisLogSource:KinesisLogSource", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private KinesisLogSource(java.lang.String name, Output<java.lang.String> id, @Nullable KinesisLogSourceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sumologic:index/kinesisLogSource:KinesisLogSource", name, state, makeResourceOptions(options, id), false);
    }

    private static KinesisLogSourceArgs makeArgs(KinesisLogSourceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? KinesisLogSourceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .aliases(List.of(
                Output.of(Alias.builder().type("sumologic:index/kineisLogSource:KineisLogSource").build())
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static KinesisLogSource get(java.lang.String name, Output<java.lang.String> id, @Nullable KinesisLogSourceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new KinesisLogSource(name, id, state, options);
    }
}
