// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic.Inputs
{

    public sealed class ContentPermissionPermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Content permission name. Valid values are `View`, `GrantView`,
        /// `Edit`, `GrantEdit`, `Manage`, and `GrantManage`. You can read more about permission levels
        /// [here](https://help.sumologic.com/Manage/Content_Sharing/Share-Content#available-permission-levels).
        /// </summary>
        [Input("permissionName", required: true)]
        public Input<string> PermissionName { get; set; } = null!;

        /// <summary>
        /// An identifier that belongs to the source type chosen above. For example,
        /// if the `sourceType` is set to `user`, `sourceId` should be identifier of the user you want to share
        /// content with (same goes for role and org source type).
        /// </summary>
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        /// <summary>
        /// Type of source for the permission. Valid values are `user`, `role`,
        /// and `org`.
        /// </summary>
        [Input("sourceType", required: true)]
        public Input<string> SourceType { get; set; } = null!;

        public ContentPermissionPermissionArgs()
        {
        }
        public static new ContentPermissionPermissionArgs Empty => new ContentPermissionPermissionArgs();
    }
}
