// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic.Inputs
{

    public sealed class DashboardPanelSumoSearchPanelQueryMetricsQueryDataArgs : global::Pulumi.ResourceArgs
    {
        [Input("aggregationType")]
        public Input<string>? AggregationType { get; set; }

        [Input("filters", required: true)]
        private InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataFilterArgs>? _filters;
        public InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataFilterArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataFilterArgs>());
            set => _filters = value;
        }

        [Input("groupBy")]
        public Input<string>? GroupBy { get; set; }

        [Input("metric", required: true)]
        public Input<string> Metric { get; set; } = null!;

        [Input("operators")]
        private InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataOperatorArgs>? _operators;
        public InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataOperatorArgs> Operators
        {
            get => _operators ?? (_operators = new InputList<Inputs.DashboardPanelSumoSearchPanelQueryMetricsQueryDataOperatorArgs>());
            set => _operators = value;
        }

        public DashboardPanelSumoSearchPanelQueryMetricsQueryDataArgs()
        {
        }
        public static new DashboardPanelSumoSearchPanelQueryMetricsQueryDataArgs Empty => new DashboardPanelSumoSearchPanelQueryMetricsQueryDataArgs();
    }
}
