// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic.Inputs
{

    public sealed class LogSearchScheduleParseableTimeRangeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// (Block List, Max: 1, Optional) Bounded time range. See
        /// begin_bounded_time_range schema schema for details.
        /// </summary>
        [Input("beginBoundedTimeRange")]
        public Input<Inputs.LogSearchScheduleParseableTimeRangeBeginBoundedTimeRangeGetArgs>? BeginBoundedTimeRange { get; set; }

        /// <summary>
        /// (Block List, Max: 1, Optional) Literal time range. See
        /// complete_literal_time_range schema for details.
        /// </summary>
        [Input("completeLiteralTimeRange")]
        public Input<Inputs.LogSearchScheduleParseableTimeRangeCompleteLiteralTimeRangeGetArgs>? CompleteLiteralTimeRange { get; set; }

        public LogSearchScheduleParseableTimeRangeGetArgs()
        {
        }
        public static new LogSearchScheduleParseableTimeRangeGetArgs Empty => new LogSearchScheduleParseableTimeRangeGetArgs();
    }
}
