// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic.Inputs
{

    public sealed class MutingScheduleMonitorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// True if the schedule applies to all monitors
        /// 
        /// [1]: https://help.sumologic.com/docs/alerts/monitors/muting-schedules/
        /// </summary>
        [Input("all")]
        public Input<bool>? All { get; set; }

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// List of monitor Ids in hex. Must be empty if `all` is true.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        public MutingScheduleMonitorArgs()
        {
        }
        public static new MutingScheduleMonitorArgs Empty => new MutingScheduleMonitorArgs();
    }
}
