// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SumoLogic.Inputs
{

    public sealed class ScanBudgetScopeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("excludedRoles")]
        private InputList<string>? _excludedRoles;
        public InputList<string> ExcludedRoles
        {
            get => _excludedRoles ?? (_excludedRoles = new InputList<string>());
            set => _excludedRoles = value;
        }

        [Input("excludedUsers")]
        private InputList<string>? _excludedUsers;
        public InputList<string> ExcludedUsers
        {
            get => _excludedUsers ?? (_excludedUsers = new InputList<string>());
            set => _excludedUsers = value;
        }

        [Input("includedRoles")]
        private InputList<string>? _includedRoles;
        public InputList<string> IncludedRoles
        {
            get => _includedRoles ?? (_includedRoles = new InputList<string>());
            set => _includedRoles = value;
        }

        [Input("includedUsers")]
        private InputList<string>? _includedUsers;
        public InputList<string> IncludedUsers
        {
            get => _includedUsers ?? (_includedUsers = new InputList<string>());
            set => _includedUsers = value;
        }

        public ScanBudgetScopeGetArgs()
        {
        }
        public static new ScanBudgetScopeGetArgs Empty => new ScanBudgetScopeGetArgs();
    }
}
