// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides the ability to create, read, delete, update connections.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sumologic from "@pulumi/sumologic";
 *
 * const connection = new sumologic.Connection("connection", {
 *     type: "WebhookConnection",
 *     description: "My description",
 *     url: "https://connection-endpoint.com",
 *     headers: {
 *         "X-Header": "my-header",
 *     },
 *     customHeaders: {
 *         "X-custom": "my-custom-header",
 *     },
 *     defaultPayload: `{
 *   "client" : "Sumo Logic",
 *   "eventType" : "{{Name}}",
 *   "description" : "{{Description}}",
 *   "search_url" : "{{QueryUrl}}",
 *   "num_records" : "{{NumRawResults}}",
 *   "search_results" : "{{AggregateResultsJson}}"
 * }
 * `,
 *     webhookType: "Webhook",
 * });
 * ```
 * ## Argument reference
 *
 * The following arguments are supported:
 *
 * - `type` - (Required) Type of connection. Only `WebhookConnection` is implemented right now.
 * - `name` - (Required) Name of connection. Name should be a valid alphanumeric value.
 * - `description` - (Optional) Description of the connection.
 * - `url` - (Required) URL for the webhook connection.
 * - `headers` - (Optional) Map of access authorization headers.
 * - `customHeaders` - (Optional) Map of custom webhook headers
 * - `defaultPayload` - (Required) Default payload of the webhook.
 * - `connectionSubtype` - (Optional) The subtype of the connection. Valid values are `Incident` and `Event`. NOTE: This is only used for the `ServiceNow` webhook type.
 * - `webhookType` - (Optional) Type of webhook. Valid values are `AWSLambda`, `Azure`, `Datadog`, `HipChat`, `PagerDuty`, `Slack`, `Webhook`, `NewRelic`, `MicrosoftTeams`, and `ServiceNow`. Default: `Webhook`
 *
 * Additional data provided in state
 *
 * - `id` - (Computed) The Id for this connection.
 *
 * ## Import
 *
 * Connections can be imported using the connection id, e.g.hcl
 *
 * ```sh
 *  $ pulumi import sumologic:index/connection:Connection test 1234567890
 * ```
 */
export class Connection extends pulumi.CustomResource {
    /**
     * Get an existing Connection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectionState, opts?: pulumi.CustomResourceOptions): Connection {
        return new Connection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sumologic:index/connection:Connection';

    /**
     * Returns true if the given object is an instance of Connection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Connection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Connection.__pulumiType;
    }

    public readonly connectionSubtype!: pulumi.Output<string | undefined>;
    public readonly customHeaders!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly defaultPayload!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly headers!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly type!: pulumi.Output<string>;
    public readonly url!: pulumi.Output<string>;
    public readonly webhookType!: pulumi.Output<string | undefined>;

    /**
     * Create a Connection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectionArgs | ConnectionState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectionState | undefined;
            inputs["connectionSubtype"] = state ? state.connectionSubtype : undefined;
            inputs["customHeaders"] = state ? state.customHeaders : undefined;
            inputs["defaultPayload"] = state ? state.defaultPayload : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["headers"] = state ? state.headers : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["type"] = state ? state.type : undefined;
            inputs["url"] = state ? state.url : undefined;
            inputs["webhookType"] = state ? state.webhookType : undefined;
        } else {
            const args = argsOrState as ConnectionArgs | undefined;
            if ((!args || args.defaultPayload === undefined) && !opts.urn) {
                throw new Error("Missing required property 'defaultPayload'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            inputs["connectionSubtype"] = args ? args.connectionSubtype : undefined;
            inputs["customHeaders"] = args ? args.customHeaders : undefined;
            inputs["defaultPayload"] = args ? args.defaultPayload : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["headers"] = args ? args.headers : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["type"] = args ? args.type : undefined;
            inputs["url"] = args ? args.url : undefined;
            inputs["webhookType"] = args ? args.webhookType : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Connection.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Connection resources.
 */
export interface ConnectionState {
    connectionSubtype?: pulumi.Input<string>;
    customHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    defaultPayload?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
    webhookType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Connection resource.
 */
export interface ConnectionArgs {
    connectionSubtype?: pulumi.Input<string>;
    customHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    defaultPayload: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    type: pulumi.Input<string>;
    url: pulumi.Input<string>;
    webhookType?: pulumi.Input<string>;
}
