// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Sets the [Sumologic Password Policy](https://help.sumologic.com/Manage/Security/Set-the-Password-Policy). Since there is only a single password policy for an organization,
 * please ensure that only a single instance of such resource is defined.
 * The behavior for defining more than one password policy resources is undefined.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sumologic from "@pulumi/sumologic";
 *
 * const examplePasswordPolicy = new sumologic.PasswordPolicy("examplePasswordPolicy", {
 *     accountLockoutDurationInMins: 30,
 *     accountLockoutThreshold: 6,
 *     failedLoginResetDurationInMins: 10,
 *     maxLength: 128,
 *     maxPasswordAgeInDays: 365,
 *     minLength: 8,
 *     minUniquePasswords: 10,
 *     mustContainDigits: true,
 *     mustContainLowercase: true,
 *     mustContainSpecialChars: true,
 *     mustContainUppercase: true,
 *     rememberMfa: true,
 *     requireMfa: false,
 * });
 * ```
 * ## Argument reference
 *
 * The following arguments are supported:
 *
 * - `minLength` - (Optional) The minimum length of the password. Defaults to 8.
 * - `maxLength` - (Optional) The maximum length of the password. Defaults to 128.
 * - `mustContainLowercase` - (Optional) If the password must contain lower case characters. Defaults to true.
 * - `mustContainUppercase` - (Optional) If the password must contain upper case characters. Defaults to true.
 * - `mustContainDigits` - (Optional) If the password must contain digits. Defaults to true.
 * - `mustContainSpecialChars` - (Optional) If the password must contain special characters. Defaults to true.
 * - `maxPasswordAgeInDays` - (Optional) Maximum number of days that a password can be used before user is required to change it. Put -1 if the user should not have to change their password. Defaults to 365.
 * - `minUniquePasswords` - (Optional) The minimum number of unique new passwords that a user must use before an old password can be reused. Defaults to 10.
 * - `accountLockoutThreshold` - (Optional) Number of failed login attempts allowed before account is locked-out. Defaults to 6.
 * - `failedLoginResetDurationInMins` - (Optional) The duration of time in minutes that must elapse from the first failed login attempt after which failed login count is reset to 0. Defaults to 10.
 * - `accountLockoutDurationInMins` - (Optional) The duration of time in minutes that a locked-out account remained locked before getting unlocked automatically. Defaults to 30.
 * - `requireMfa` - (Optional) If MFA should be required to log in. Defaults to false.
 * - `rememberMfa` - (Optional) If MFA should be remembered on the browser. Defaults to true.
 *
 * [1]: https://help.sumologic.com/Manage/Security/Set-the-Password-Policy
 */
export class PasswordPolicy extends pulumi.CustomResource {
    /**
     * Get an existing PasswordPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PasswordPolicyState, opts?: pulumi.CustomResourceOptions): PasswordPolicy {
        return new PasswordPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sumologic:index/passwordPolicy:PasswordPolicy';

    /**
     * Returns true if the given object is an instance of PasswordPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PasswordPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PasswordPolicy.__pulumiType;
    }

    public readonly accountLockoutDurationInMins!: pulumi.Output<number | undefined>;
    public readonly accountLockoutThreshold!: pulumi.Output<number | undefined>;
    public readonly failedLoginResetDurationInMins!: pulumi.Output<number | undefined>;
    public readonly maxLength!: pulumi.Output<number | undefined>;
    public readonly maxPasswordAgeInDays!: pulumi.Output<number | undefined>;
    public readonly minLength!: pulumi.Output<number | undefined>;
    public readonly minUniquePasswords!: pulumi.Output<number | undefined>;
    public readonly mustContainDigits!: pulumi.Output<boolean | undefined>;
    public readonly mustContainLowercase!: pulumi.Output<boolean | undefined>;
    public readonly mustContainSpecialChars!: pulumi.Output<boolean | undefined>;
    public readonly mustContainUppercase!: pulumi.Output<boolean | undefined>;
    public readonly rememberMfa!: pulumi.Output<boolean | undefined>;
    public readonly requireMfa!: pulumi.Output<boolean | undefined>;

    /**
     * Create a PasswordPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PasswordPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PasswordPolicyArgs | PasswordPolicyState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PasswordPolicyState | undefined;
            inputs["accountLockoutDurationInMins"] = state ? state.accountLockoutDurationInMins : undefined;
            inputs["accountLockoutThreshold"] = state ? state.accountLockoutThreshold : undefined;
            inputs["failedLoginResetDurationInMins"] = state ? state.failedLoginResetDurationInMins : undefined;
            inputs["maxLength"] = state ? state.maxLength : undefined;
            inputs["maxPasswordAgeInDays"] = state ? state.maxPasswordAgeInDays : undefined;
            inputs["minLength"] = state ? state.minLength : undefined;
            inputs["minUniquePasswords"] = state ? state.minUniquePasswords : undefined;
            inputs["mustContainDigits"] = state ? state.mustContainDigits : undefined;
            inputs["mustContainLowercase"] = state ? state.mustContainLowercase : undefined;
            inputs["mustContainSpecialChars"] = state ? state.mustContainSpecialChars : undefined;
            inputs["mustContainUppercase"] = state ? state.mustContainUppercase : undefined;
            inputs["rememberMfa"] = state ? state.rememberMfa : undefined;
            inputs["requireMfa"] = state ? state.requireMfa : undefined;
        } else {
            const args = argsOrState as PasswordPolicyArgs | undefined;
            inputs["accountLockoutDurationInMins"] = args ? args.accountLockoutDurationInMins : undefined;
            inputs["accountLockoutThreshold"] = args ? args.accountLockoutThreshold : undefined;
            inputs["failedLoginResetDurationInMins"] = args ? args.failedLoginResetDurationInMins : undefined;
            inputs["maxLength"] = args ? args.maxLength : undefined;
            inputs["maxPasswordAgeInDays"] = args ? args.maxPasswordAgeInDays : undefined;
            inputs["minLength"] = args ? args.minLength : undefined;
            inputs["minUniquePasswords"] = args ? args.minUniquePasswords : undefined;
            inputs["mustContainDigits"] = args ? args.mustContainDigits : undefined;
            inputs["mustContainLowercase"] = args ? args.mustContainLowercase : undefined;
            inputs["mustContainSpecialChars"] = args ? args.mustContainSpecialChars : undefined;
            inputs["mustContainUppercase"] = args ? args.mustContainUppercase : undefined;
            inputs["rememberMfa"] = args ? args.rememberMfa : undefined;
            inputs["requireMfa"] = args ? args.requireMfa : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(PasswordPolicy.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PasswordPolicy resources.
 */
export interface PasswordPolicyState {
    readonly accountLockoutDurationInMins?: pulumi.Input<number>;
    readonly accountLockoutThreshold?: pulumi.Input<number>;
    readonly failedLoginResetDurationInMins?: pulumi.Input<number>;
    readonly maxLength?: pulumi.Input<number>;
    readonly maxPasswordAgeInDays?: pulumi.Input<number>;
    readonly minLength?: pulumi.Input<number>;
    readonly minUniquePasswords?: pulumi.Input<number>;
    readonly mustContainDigits?: pulumi.Input<boolean>;
    readonly mustContainLowercase?: pulumi.Input<boolean>;
    readonly mustContainSpecialChars?: pulumi.Input<boolean>;
    readonly mustContainUppercase?: pulumi.Input<boolean>;
    readonly rememberMfa?: pulumi.Input<boolean>;
    readonly requireMfa?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a PasswordPolicy resource.
 */
export interface PasswordPolicyArgs {
    readonly accountLockoutDurationInMins?: pulumi.Input<number>;
    readonly accountLockoutThreshold?: pulumi.Input<number>;
    readonly failedLoginResetDurationInMins?: pulumi.Input<number>;
    readonly maxLength?: pulumi.Input<number>;
    readonly maxPasswordAgeInDays?: pulumi.Input<number>;
    readonly minLength?: pulumi.Input<number>;
    readonly minUniquePasswords?: pulumi.Input<number>;
    readonly mustContainDigits?: pulumi.Input<boolean>;
    readonly mustContainLowercase?: pulumi.Input<boolean>;
    readonly mustContainSpecialChars?: pulumi.Input<boolean>;
    readonly mustContainUppercase?: pulumi.Input<boolean>;
    readonly rememberMfa?: pulumi.Input<boolean>;
    readonly requireMfa?: pulumi.Input<boolean>;
}
