// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the sumologic package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'sumologic';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }


    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.accessId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'accessId'");
            }
            if ((!args || args.accessKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'accessKey'");
            }
            inputs["accessId"] = args ? args.accessId : undefined;
            inputs["accessKey"] = args ? args.accessKey : undefined;
            inputs["adminMode"] = pulumi.output(args ? args.adminMode : undefined).apply(JSON.stringify);
            inputs["baseUrl"] = (args ? args.baseUrl : undefined) ?? utilities.getEnv("SUMOLOGIC_BASE_URL");
            inputs["environment"] = (args ? args.environment : undefined) ?? utilities.getEnv("SUMOLOGIC_ENVIRONMENT");
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Provider.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    readonly accessId: pulumi.Input<string>;
    readonly accessKey: pulumi.Input<string>;
    readonly adminMode?: pulumi.Input<boolean>;
    readonly baseUrl?: pulumi.Input<string>;
    readonly environment?: pulumi.Input<string>;
}
